version: '3.3'

services:
  frontend:
    build: ./front-end
    ports: 
      - 3000:3000

  cms:
    build: ./strapi
    ports:
      - 1337:1337

  nginx:
    build: ./nginx
    ports:
      - 80:80