name: Deploy to Cloud Run from Source (blog)

on: workflow_dispatch

env:
  PROJECT_ID: snaga-solutions # TODO: update Google Cloud project id
  SERVICE: client # TODO: update Cloud Run service name
  REGION: europe-west1 # TODO: update Cloud Run service region

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_GRIDSOME_GOOGLE_ANALYTIC_ID: ${{ secrets.GOOGLE_ANALYTIC_ID }}
          directory: ./front-end
          file_name: .env
          fail_on_empty: false
      
      - name: Read
        run: |
          cd ./front-end
          cat .env
          cat package.json

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./front-end
          env_vars: |
            GRIDSOME_GOOGLE_ANALYTIC_ID=${{ secrets.GOOGLE_ANALYTIC_ID }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
