name: Checking eslint
on:  
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize, assigned]
env:
  FRONT_DIR: front-end
jobs:
  front-lint:
    runs-on: ubuntu-latest
    steps:
     - name: Get repository code
       uses: actions/checkout@v3

     - name: Install deps
       working-directory: ${{ env.FRONT_DIR }}
       run: yarn install --frozen-lockfile

     - name: Lint code
       working-directory: ${{ env.FRONT_DIR }}
       run: yarn lint